name: "Docker Ruval generator"
author: "Diego Ruvalcaba"
description: "Generated a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The commiter's email address
    require: true
    default: ${{ github.actor }}@localhost
  user:
    description: The commiter's name
    require: true
    default: ${{ github.actor }}
